# _config.yml
title: 桜Index - 公式サイト
url: https://sakuraindex.github.io
baseurl: /Sakura-Index-Site   # ← プロジェクトサイトの場合は必須

exclude:
  - README.md
  - scripts
  - node_modules
  - .github

# Liquid / Jekyll の安全対策
markdown: kramdown
highlighter: rouge
timezone: Asia/Tokyo
